#!/bin/bash
# First-time setup: writes deploy/.env with fresh random database passwords
# and asks for the few settings that differ per installation. Then:
#   docker compose up -d
#
#   ./setup.sh            interactive
#   ./setup.sh --defaults accept every default (e.g. in scripts)
set -euo pipefail
cd "$(dirname "$0")"

if [ -f .env ]; then
    echo ".env already exists; to change the database password use tools/change-db-password.sh" >&2
    exit 1
fi

random() { head -c 32 /dev/urandom | base64 | tr -d '/+=\n' | cut -c1-24; }
ask() {
    local prompt=$1 default=$2 answer
    if [ "${DEFAULTS:-}" = 1 ]; then echo "$default"; return; fi
    read -r -p "$prompt [$default]: " answer
    echo "${answer:-$default}"
}
[ "${1:-}" = "--defaults" ] && DEFAULTS=1

hostname=$(ask "Host name browsers use for the admin console (HTTPS certificate)" localhost)
backup_time=$(ask "Daily backup time (HH:MM)" 01:30)
backup_days=$(ask "Days of backups to keep" 14)

umask 077
cat > .env <<ENV
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M'). Keep this file private.

# MySQL: root and the account Hermes uses (change later with
# tools/change-db-password.sh, not by editing here)
DB_ROOT_PASSWORD=$(random)
HERMES_DB_USER=hermes
HERMES_DB_PASSWORD=$(random)

# HTTPS certificate generated on first start (replace it from the admin
# console: Main > HTTPS Certificate)
APP_TLS_HOSTNAME=$hostname

# backups written to deploy/backups
BACKUP_TIME=$backup_time
BACKUP_KEEP_DAYS=$backup_days
BACKUP_UID=$(id -u)
BACKUP_GID=$(id -g)
ENV
mkdir -p backups
echo "Wrote deploy/.env. Start with: docker compose up -d"
echo "Then sign in at https://$hostname:18443/corvus/admin/home as admin / admin (you will be asked to change it)."
