CREATE TABLE partnership (
	partnership_id varchar(200),
	cpa_id varchar(200),
	service varchar(200),
	action varchar(200),
	transport_protocol varchar(200),
	transport_endpoint varchar(200),
	is_hostname_verified varchar(200),
	sync_reply_mode varchar(200),
	ack_requested varchar(200),
	ack_sign_requested varchar(200),
	dup_elimination varchar(200),
	actor varchar(200),
	disabled varchar(200),
	retries integer,
	retry_interval integer,
	persist_duration varchar(200),
	message_order varchar(200),
	sign_requested varchar(200),
	sign_cert binary,
	ds_algorithm varchar(200),
	md_algorithm varchar(200),
	encrypt_requested varchar(200),
	encrypt_cert binary,
	encrypt_algorithm varchar(200),
	PRIMARY KEY (partnership_id)
);
