-- Oracle Database 23ai or later (BOOLEAN, IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS sfrm_ftp_channel (
	channel_id varchar2(50) NOT NULL,
	name varchar2(200) NOT NULL,
	host varchar2(255) NOT NULL,
	port number(10) DEFAULT 21 NOT NULL,
	username varchar2(200),
	password_encrypted varchar2(1000),
	remote_path varchar2(500) DEFAULT '/' NOT NULL,
	is_passive_mode boolean DEFAULT true NOT NULL,
	use_tls boolean DEFAULT false NOT NULL,
	tls_cert_fingerprint varchar2(200),
	polling_interval number(10),
	max_files_per_poll number(10),
	is_disabled boolean DEFAULT false NOT NULL,
	description varchar2(500),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (channel_id)
);

CREATE TABLE IF NOT EXISTS sfrm_sftp_channel (
	channel_id varchar2(50) NOT NULL,
	name varchar2(200) NOT NULL,
	host varchar2(255) NOT NULL,
	port number(10) DEFAULT 22 NOT NULL,
	username varchar2(200),
	password_encrypted varchar2(1000),
	remote_path varchar2(500) DEFAULT '/' NOT NULL,
	host_key_fingerprint varchar2(200),
	polling_interval number(10),
	max_files_per_poll number(10),
	is_disabled boolean DEFAULT false NOT NULL,
	description varchar2(500),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (channel_id)
);

CREATE TABLE IF NOT EXISTS sfrm_file_polling_channel (
	channel_id varchar2(50) NOT NULL,
	name varchar2(200) NOT NULL,
	watch_path varchar2(500) NOT NULL,
	polling_interval number(10),
	max_files_per_poll number(10),
	is_disabled boolean DEFAULT false NOT NULL,
	description varchar2(500),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (channel_id)
);

CREATE TABLE IF NOT EXISTS sfrm_mail_channel (
	channel_id varchar2(50) NOT NULL,
	name varchar2(200) NOT NULL,
	protocol varchar2(10) DEFAULT 'imap' NOT NULL,
	host varchar2(255) NOT NULL,
	port number(10),
	username varchar2(200),
	password_encrypted varchar2(1000),
	folder varchar2(200) DEFAULT 'INBOX' NOT NULL,
	use_ssl boolean DEFAULT true NOT NULL,
	polling_interval number(10),
	max_messages_per_poll number(10),
	is_disabled boolean DEFAULT false NOT NULL,
	description varchar2(500),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (channel_id)
);

CREATE TABLE IF NOT EXISTS sfrm_partnership (
	partnership_seq number(10) GENERATED BY DEFAULT AS IDENTITY,
	partnership_id varchar2(50) NOT NULL,
	description varchar2(200),
	partner_endpoint varchar2(200) NOT NULL,
	partner_cert_fingerprint varchar2(200),
	is_hostname_verified boolean DEFAULT false,
	sign_algorithm varchar2(200),
	encrypt_algorithm varchar2(200),
	retry_max number(10) DEFAULT 3,
	retry_interval number(10) DEFAULT 30000,
	is_disabled boolean DEFAULT false NOT NULL,
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	modified_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (partnership_seq),
	UNIQUE (partnership_id)
);

CREATE TABLE IF NOT EXISTS sfrm_message (
	message_id varchar2(200) NOT NULL,
	message_box varchar2(200) NOT NULL,
	partnership_id varchar2(50) NOT NULL,
	partner_endpoint varchar2(200) NOT NULL,
	total_segment number(10),
	total_size number(19),
	is_hostname_verified boolean,
	partner_cert_content varchar2(200),
	sign_algorithm varchar2(200),
	encrypt_algorithm varchar2(200),
	status varchar2(200) NOT NULL,
	status_desc varchar2(200),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	proceed_timestamp timestamp,
	completed_timestamp timestamp,
	filename varchar2(200),
	PRIMARY KEY (message_id, message_box)
);

CREATE TABLE IF NOT EXISTS sfrm_message_segment (
	message_id varchar2(200) NOT NULL,
	message_box varchar2(200) NOT NULL,
	segment_no number(10) NOT NULL,
	segment_type varchar2(200) NOT NULL,
	segment_start number(19),
	segment_end number(19),
	retried number(10) DEFAULT -1,
	md5_value varchar2(200),
	status varchar2(200),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	proceed_timestamp timestamp,
	completed_timestamp timestamp,
	PRIMARY KEY (message_id, message_box, segment_no, segment_type)
);
