-- Oracle Database 23ai or later (BOOLEAN, IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS listener_port (
	port_id varchar2(50) NOT NULL,
	name varchar2(200) NOT NULL,
	bind_address varchar2(100) DEFAULT '0.0.0.0' NOT NULL,
	port number(10) NOT NULL,
	use_tls boolean DEFAULT false NOT NULL,
	target_service varchar2(20) NOT NULL,
	is_disabled boolean DEFAULT false NOT NULL,
	description varchar2(500),
	created_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (port_id)
);

CREATE TABLE IF NOT EXISTS ca_issued_cert (
	serial_number varchar2(50) NOT NULL,
	subject_dn varchar2(500) NOT NULL,
	cert blob NOT NULL,
	revoked boolean DEFAULT false NOT NULL,
	issued_timestamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	revoked_timestamp timestamp,
	PRIMARY KEY (serial_number)
);

-- admin console: who did what (Access > Audit Log)
CREATE TABLE IF NOT EXISTS audit_log (
	audit_id number(19) GENERATED BY DEFAULT AS IDENTITY,
	event_time timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	username varchar2(64),
	client_ip varchar2(64),
	action varchar2(100) NOT NULL,
	target varchar2(500),
	outcome varchar2(20) NOT NULL,
	detail varchar2(1000),
	PRIMARY KEY (audit_id)
);
CREATE INDEX IF NOT EXISTS audit_log_time ON audit_log (event_time);
CREATE INDEX IF NOT EXISTS audit_log_user ON audit_log (username);

-- admin console: per-user password age/history and two-factor secret
CREATE TABLE IF NOT EXISTS console_user_security (
	username varchar2(64) NOT NULL,
	password_changed timestamp,
	password_history varchar2(4000),
	totp_secret varchar2(64),
	totp_enabled varchar2(5) DEFAULT 'false' NOT NULL,
	totp_last_step number(19),
	PRIMARY KEY (username)
);

-- admin console: security settings (Access > Security Settings)
CREATE TABLE IF NOT EXISTS console_setting (
	name varchar2(64) NOT NULL,
	value varchar2(500),
	PRIMARY KEY (name)
);
