#!/bin/sh
# Sourced from setenv.sh on every Tomcat start: (re)writes tomcat-users.xml
# from the environment so no default password ships in the image.
#
#   APP_ADMIN_USER / APP_ADMIN_PASSWORD   admin console login (default user: corvus)
#   APP_API_USER   / APP_API_PASSWORD     REST API login      (default user: apiuser)
#
# A password left unset is generated once and kept in $CREDENTIALS_FILE (on
# the repository volume, so it survives container re-creation); read it with
#   docker exec <container> cat /hermes_home/repository/.credentials

CREDENTIALS_FILE=/hermes_home/repository/.credentials
TOMCAT_USERS=/etc/tomcat8/tomcat-users.xml

random_password() {
    head -c 24 /dev/urandom | base64 | tr -d '/+=\n' | cut -c1-24
}

# value of KEY in the credentials file, if any
saved() {
    [ -f "$CREDENTIALS_FILE" ] && sed -n "s/^$1=//p" "$CREDENTIALS_FILE" | head -n 1
}

xml_escape() {
    printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

admin_user=${APP_ADMIN_USER:-corvus}
api_user=${APP_API_USER:-apiuser}
admin_password=${APP_ADMIN_PASSWORD:-$(saved ADMIN_PASSWORD)}
api_password=${APP_API_PASSWORD:-$(saved API_PASSWORD)}

generated=false
if [ -z "$admin_password" ]; then
    admin_password=$(random_password)
    generated=true
fi
if [ -z "$api_password" ]; then
    api_password=$(random_password)
    generated=true
fi

mkdir -p "$(dirname "$CREDENTIALS_FILE")"
umask 077
{
    echo "ADMIN_USER=$admin_user"
    echo "ADMIN_PASSWORD=$admin_password"
    echo "API_USER=$api_user"
    echo "API_PASSWORD=$api_password"
} > "$CREDENTIALS_FILE"
if [ "$generated" = true ]; then
    echo "admin-credentials: generated password(s) saved in $CREDENTIALS_FILE" >&2
fi

cat > "$TOMCAT_USERS" <<EOF
<?xml version='1.0' encoding='utf-8'?>
<!-- Generated by admin-credentials.sh at startup; edits here are overwritten. -->
<tomcat-users>
  <role rolename="tomcat"/>
  <role rolename="admin"/>
  <role rolename="api"/>
  <role rolename="user"/>
  <user username="$(xml_escape "$admin_user")" password="$(xml_escape "$admin_password")" roles="tomcat,admin,user"/>
  <user username="$(xml_escape "$api_user")" password="$(xml_escape "$api_password")" roles="api"/>
</tomcat-users>
EOF
chown root:tomcat8 "$TOMCAT_USERS"
chmod 640 "$TOMCAT_USERS"
umask 022
unset admin_password api_password
